#!/usr/bin/env bash
# Configure HAproxy configuration file to automatically redirect HTTP traffic to HTTPS

global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon
    
    tune.ssl.default-dh-param 2048

defaults
    log global
    option httplog
    option dontlognull
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

# Frontend for handling HTTP requests and redirecting to HTTPS
frontend http_front
    bind *:80
    mode http
    redirect scheme https code 301 if !{ ssl_fc }

# Frontend for handling HTTPS requests
frontend https_front
    bind *:443 ssl crt /etc/haproxy/certs/www.gaddiel.tech.pem
    mode http
    default_backend web_servers

# Backend for the web servers
backend web_servers
    balance roundrobin
    server web-01 100.27.27.252:80 check
    server web-02 18.208.133.92:80 check
